listen: ":8989"

authn:
  jwt:
    secret: "qwerty"
    field: "username"

authz:
  ldap:
    url: "ldap://localhost:389"
    username: "cn=read-only-admin,dc=example,dc=com"
    password: "password"

backends:
  - name: some_backend
    host: "localhost"
    port: 8080
    scheme: "http"

routes:
- match:
    prefix: "/" # To be implemented
    host: "abc" # "*" to match all hosts
  backend: some_backend