listen: ":8989"

authn:
  jwt:
    secret: "qwerty"
    field: "username"

authz:
  ldap:
    url: "ldap://localhost:389"
    username: "cn=readonly,dc=example,dc=org"
    password: "readonly"
    base_dn: "dc=example,dc=org"
  acl:
    - action: allow
      users:
        - jdoe
      routes:
        - /hello


backends:
  - name: some_backend
    host: "localhost"
    port: 8080
    scheme: "http"

routes:
- match:
    host: "*" # "*" to match all hosts
  backend: some_backend