listen: ":8989"

authn:
  jwt:
    secret: "qwerty" # JWT secret
    field: "username" # JSON field in payload which identifies user

authz:
  ldap:
    url: "ldap://localhost:389"
    username: "cn=readonly,dc=example,dc=org"
    password: "readonly"
    base_dn: "dc=example,dc=org"
    filter: "(uid=%s)" # LDAP filter, C-style format string
  acl: # ACL list, support only allow actionm default action deny
    - action: allow
      users:
        - jdoe
      routes: # Exact matches
        - /hello


backends:
  - name: some_backend
    host: "localhost"
    port: 8080
    scheme: "http"

routes:
- match:
    host: "*" # "*" to match all hosts
  backend: some_backend